FROM nginx:1.19
RUN mkdir /var/www

# COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
# COPY ./nginx/conf.d /etc/nginx/conf.d
# COPY ./letsencrypt/fullchain.pem /etc/nginx/letsencrypt/fullchain.pem
# COPY ./letsencrypt/privkey.pem /etc/nginx/letsencrypt/privkey.pem